name: ShellCheck

on:
  push:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up ShellCheck
      run: |
        sudo apt-get update -qy
        sudo apt-get install -y shellcheck

    - name: Run ShellCheck
      run: shellcheck **/*.sh